import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext(null)

export const translations = {
  bn: {
    // Sidebar
    dashboard: 'ড্যাশবোর্ড',
    articles: 'আর্টিকেল',
    workflow: 'ওয়ার্কফ্লো',
    reports: 'পারফরম্যান্স রিপোর্ট',
    versions: 'ভার্সন হিস্ট্রি',
    newsSort: 'নিউজ সাজান',
    media: 'মিডিয়া',
    users: 'ব্যবহারকারী',
    settings: 'সেটিংস',
    masterData: 'মাস্টার ডেটা',
    logout: 'লগআউট',

    // Topbar
    notifications: 'নোটিফিকেশন',
    noNotifications: 'কোনো নোটিফিকেশন নেই',
    markAllRead: 'সব পড়া হয়েছে',

    // Login
    loginTitle: 'লগইন করুন',
    loginSubtitle: 'আপনার ভূমিকা বেছে নিন এবং প্রবেশ করুন',
    whoAreYou: 'আপনি কে?',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    loginBtn: 'লগইন করুন',
    loggingIn: 'লগইন হচ্ছে...',
    invalidCredentials: 'ইমেইল বা পাসওয়ার্ড সঠিক নয়',
    demoSystem: 'Demo সিস্টেম — শুধুমাত্র পরীক্ষামূলক ব্যবহারের জন্য',
    enterEmail: 'আপনার ইমেইল লিখুন...',
    selectRole: 'পজিশন বেছে নিন',

    // Role labels
    superAdmin: 'সুপার অ্যাডমিন',
    admin: 'অ্যাডমিন',
    chiefEditor: 'চিফ এডিটর',
    editor: 'এডিটর',
    reporter: 'রিপোর্টার',

    // ArticleList
    allArticles: 'সব আর্টিকেল',
    searchArticles: 'আর্টিকেল বা ক্যাটাগরি খুঁজুন...',
    allStatus: 'সব স্ট্যাটাস',
    published: 'প্রকাশিত',
    approved: 'অনুমোদিত',
    inReview: 'রিভিউতে',
    writing: 'লেখা হচ্ছে',
    correction: 'কারেকশন',
    draft: 'ড্রাফট',
    title: 'শিরোনাম',
    category: 'ক্যাটাগরি',
    status: 'স্ট্যাটাস',
    date: 'তারিখ',
    reporter_col: 'রিপোর্টার',
    action: 'অ্যাকশন',
    noArticlesFound: 'কোনো আর্টিকেল পাওয়া যায়নি',
    unnamed: 'শিরোনামহীন',

    // NewsSort
    sortNews: 'নিউজ সাজান',
    sortDesc: 'ড্র্যাগ করে ক্রম নির্ধারণ করুন ও ক্যাটাগরি বেছে নিন',
    save: 'সেভ করুন',
    saved: 'সেভ হয়েছে',
    visible: 'টি দৃশ্যমান',
    total: 'টি নিউজ',
    pageAssigned: 'টিতে ক্যাটাগরি নির্ধারিত',
    noNewsInCategory: 'এই ক্যাটাগরিতে এখনো কোনো প্রকাশিত নিউজ নেই',
    publishFromWorkflow: 'Workflow থেকে একটি আর্টিকেল প্রকাশ করুন',
    assignPage: 'ক্যাটাগরি',
    pages: 'টি ক্যাটাগরি',
    selectPageTitle: 'ক্যাটাগরি নির্ধারণ করুন',
    maxPages: 'সর্বোচ্চ ৩টি ক্যাটাগরি বেছে নেওয়া যাবে',
    removeAll: 'সব সরিয়ে দিন',
    clickPageBtn: '[📄 ক্যাটাগরি] বাটনে ক্লিক করুন',

    // Workflow
    assignedTo: 'Assigned to',
    assignedBy: 'Assigned by',
    created: 'তৈরি',
    deadline: 'Deadline',
    nextStep: 'পরবর্তী পদক্ষেপ',
    timeline: 'টাইমলাইন',

    // Common
    add: 'যোগ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    edit: 'এডিট',
    search: 'খুঁজুন',
    noData: 'কোনো ডেটা নেই',
    loading: 'লোড হচ্ছে...',

    // MasterData tabs
    roles: 'রোল',
    menu: 'মেনু এক্সেস',
    categories: 'ক্যাটাগরি',
    tags: 'ট্যাগ',
    sources: 'সোর্স',
    byline: 'বায়লাইন',
    mdPages: 'পেজ',
    shifts: 'ডিউটি শিফট',
    calendar: 'শিফট ক্যালেন্ডার',
    specialdays: 'বিশেষ দিবস',
    masterDataTitle: 'মাস্টার ডেটা',

    // MasterData Content
    mdRolesDesc: 'সিস্টেমে বিভিন্ন ব্যবহারকারীর ভূমিকা নির্ধারণ করুন',
    mdMenuDesc: 'কোন রোল কোন মেনু দেখতে পাবে সেটি নির্ধারণ করুন',
    mdCatDesc: 'নিউজের ক্যাটাগরি এবং তার সাব-ক্যাটাগরি ম্যানেজ করুন',
    mdTagDesc: 'নিউজে ব্যবহারের জন্য ট্যাগ ম্যানেজ করুন',
    mdSourceDesc: 'নিউজের সোর্স বা ডেস্কের তালিকা ম্যানেজ করুন',
    mdPageDesc: 'ওয়েবসাইটের কোন কোন পেজে নিউজ প্রদর্শিত হবে সেটি নির্ধারণ করুন',
    mdShiftDesc: 'সাংবাদিকদের কর্মসময়ের শিফট নির্ধারণ করুন',
    mdCalDesc: 'সাপ্তাহিক ডিউটি শিফট নির্ধারণ করুন',
    mdSpecialDesc: 'গুরুত্বপূর্ণ দিন ও তারিখ রেকর্ড রাখুন',
    mdBylineDesc: 'নিউজে বায়লাইন হিসাবে দেখানোর জন্য সাংবাদিকদের তালিকা ম্যানেজ করুন',

    mdMenuCol: 'মেনু',
    saveChanges: 'পরিবর্তন সেভ করুন',
    saveBtn: 'সেভ করুন',
    cancelBtn: 'বাতিল',
    addNewRole: 'নতুন রোল যোগ করুন',
    searchTags: 'ট্যাগ খুঁজুন...',
    noTags: 'কোনো ট্যাগ পাওয়া যায়নি',
    newTag: 'নতুন ট্যাগের নাম...',
    addTag: 'ট্যাগ যোগ',
    newSource: 'নতুন সোর্স / ডেস্কের নাম...',
    addSource: 'সোর্স যোগ',
    newPage: 'নতুন পেজের নাম...',
    addPage: 'পেজ যোগ',
    newShift: 'নতুন শিফট যোগ করুন',
    shiftName: 'শিফটের নাম',
    startTime: 'শুরুর সময়',
    endTime: 'শেষ সময়',
    reporterCol: 'রিপোর্টার',
    everyYear: 'প্রতি বছর',
    dayName: 'দিবসের নাম',
    repeatYearly: 'প্রতি বছর পুনরাবৃত্তি হবে',
    addSpecialDay: 'নতুন বিশেষ দিবস যোগ করুন',
    searchJournalist: 'সাংবাদিক খুঁজুন...',
    namePlaceholder: 'নাম',
    designationPlaceholder: 'পদবি',
    emailOptional: 'ইমেইল (ঐচ্ছিক)',
    noJournalist: 'কোনো সাংবাদিক পাওয়া যায়নি',
    addJournalistBtn: 'নতুন সাংবাদিক যোগ করুন',
    journalistNameReq: 'সাংবাদিকের নাম *',
    desigExample: 'পদবি (যেমন: সিনিয়র রিপোর্টার)',
    subCount: 'টি সাব',
    noSubCat: 'কোনো সাব-ক্যাটাগরি নেই',
    newSubCat: 'নতুন সাব-ক্যাটাগরি...',
    newCatName: 'নতুন ক্যাটাগরির নাম...',
    addCat: 'ক্যাটাগরি যোগ',
    typeNational: 'জাতীয়',
    typeCultural: 'সাংস্কৃতিক',
    typeReligious: 'ধর্মীয়',
    typeInternational: 'আন্তর্জাতিক',

    // Dashboard
    totalArticles: 'মোট আর্টিকেল',
    pageViews: 'পেজ ভিউ',
    activeUsers: 'অ্যাক্টিভ ইউজার',
    pendingReviews: 'পেন্ডিং রিভিউ',
    today: 'আজ',
    thanYesterday: 'গতকালের চেয়ে',
    editorsWriters: 'এডিটর, রাইটার',
    needsApproval: 'অনুমোদন দরকার',

    // AssignmentBoard
    assignmentBoard: 'অ্যাসাইনমেন্ট বোর্ড',
    manageWorkflow: 'নিউজ ওয়ার্কফ্লো ম্যানেজ করুন',
    selfAssignment: 'Self Assignment',
    newAssignment: 'নতুন Assignment',
    waitingApproval: 'টি Self Assignment Approval-এর অপেক্ষায় আছে',
    view: 'দেখুন',
    totalCount: 'মোট',
    writingTab: 'লেখা চলছে',
    reviewTab: 'রিভিউ',
    approvedTab: 'অনুমোদিত',
    selfTab: 'Self',
    filterAll: 'সব',
    filterNeedsApproval: 'Approval দরকার',
    filterWaiting: 'অপেক্ষায়',
    filterWriting: 'লেখা চলছে',
    filterSubmitted: 'জমা দেওয়া',
    filterReview: 'রিভিউ',
    filterApproved: 'অনুমোদিত',
    filterCorrection: 'সংশোধন',
    filterPublished: 'প্রকাশিত',
    allTypes: 'সব ধরন',

    // Settings
    settingsDesc: 'ক্যাটাগরি, সাংবাদিক, সোর্স ও নিউজ পজিশন ম্যানেজ করুন',
    catAndSub: 'ক্যাটাগরি ও সাব-ক্যাটাগরি',
    subCatCount: 'সাব-ক্যাটাগরি',
    addCategory: 'নতুন ক্যাটাগরি যোগ করুন...',
    addBtn: '+ যোগ করুন',
    
    // Categories (Dynamic data translations)
    রাজনীতি: 'রাজনীতি',
    অর্থনীতি: 'অর্থনীতি',
    খেলাধুলা: 'খেলাধুলা',
    বিনোদন: 'বিনোদন',
    প্রযুক্তি: 'প্রযুক্তি',
    পরিবেশ: 'পরিবেশ',
    মতামত: 'মতামত',
  },

  en: {
    // Sidebar
    dashboard: 'Dashboard',
    articles: 'Articles',
    workflow: 'Workflow',
    reports: 'Performance Reports',
    versions: 'Version History',
    newsSort: 'News Order',
    media: 'Media',
    users: 'Users',
    settings: 'Settings',
    masterData: 'Master Data',
    logout: 'Logout',

    // Topbar
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',

    // Login
    loginTitle: 'Sign In',
    loginSubtitle: 'Select your role and continue',
    whoAreYou: 'Who are you?',
    email: 'Email',
    password: 'Password',
    loginBtn: 'Sign In',
    loggingIn: 'Signing in...',
    invalidCredentials: 'Invalid email or password',
    demoSystem: 'Demo system — for testing purposes only',
    enterEmail: 'Enter your email...',
    selectRole: 'Select a role to continue',

    // Role labels
    superAdmin: 'Super Admin',
    admin: 'Admin',
    chiefEditor: 'Chief Editor',
    editor: 'Editor',
    reporter: 'Reporter',

    // ArticleList
    allArticles: 'All Articles',
    searchArticles: 'Search by title or category...',
    allStatus: 'All Status',
    published: 'Published',
    approved: 'Approved',
    inReview: 'In Review',
    writing: 'Writing',
    correction: 'Correction',
    draft: 'Draft',
    title: 'Title',
    category: 'Category',
    status: 'Status',
    date: 'Date',
    reporter_col: 'Reporter',
    action: 'Action',
    noArticlesFound: 'No articles found',
    unnamed: 'Untitled',

    // NewsSort
    sortNews: 'Sort News',
    sortDesc: 'Drag to reorder and assign categories',
    save: 'Save',
    saved: 'Saved',
    visible: ' visible',
    total: ' articles',
    pageAssigned: ' with categories assigned',
    noNewsInCategory: 'No published news in this category yet',
    publishFromWorkflow: 'Publish an article from Workflow',
    assignPage: 'Category',
    pages: ' categories',
    selectPageTitle: 'Assign Category',
    maxPages: 'Maximum 3 categories allowed',
    removeAll: 'Remove all',
    clickPageBtn: 'Click [📄 Category] to assign',

    // Workflow
    assignedTo: 'Assigned to',
    assignedBy: 'Assigned by',
    created: 'Created',
    deadline: 'Deadline',
    nextStep: 'Next Step',
    timeline: 'Timeline',

    // Common
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    noData: 'No data',
    loading: 'Loading...',

    // MasterData tabs
    roles: 'Roles',
    menu: 'Menu Access',
    categories: 'Categories',
    tags: 'Tags',
    sources: 'Sources',
    byline: 'Byline',
    mdPages: 'Pages',
    shifts: 'Duty Shifts',
    calendar: 'Shift Calendar',
    specialdays: 'Special Days',
    masterDataTitle: 'Master Data',

    // MasterData Content
    mdRolesDesc: 'Define user roles and permissions in the system',
    mdMenuDesc: 'Define which role can view which menu',
    mdCatDesc: 'Manage news categories and sub-categories',
    mdTagDesc: 'Manage tags for use in news articles',
    mdSourceDesc: 'Manage the list of news sources or desks',
    mdPageDesc: 'Define which pages news will be displayed on',
    mdShiftDesc: 'Define duty shifts for journalists',
    mdCalDesc: 'Define weekly duty shifts',
    mdSpecialDesc: 'Keep record of important dates and days',
    mdBylineDesc: 'Manage the list of journalists for article bylines',

    mdMenuCol: 'Menu',
    saveChanges: 'Save Changes',
    saveBtn: 'Save',
    cancelBtn: 'Cancel',
    addNewRole: 'Add New Role',
    searchTags: 'Search tags...',
    noTags: 'No tags found',
    newTag: 'New tag name...',
    addTag: 'Add Tag',
    newSource: 'New source/desk name...',
    addSource: 'Add Source',
    newPage: 'New page name...',
    addPage: 'Add Page',
    newShift: 'Add New Shift',
    shiftName: 'Shift Name',
    startTime: 'Start Time',
    endTime: 'End Time',
    reporterCol: 'Reporter',
    everyYear: 'Every year',
    dayName: 'Day Name',
    repeatYearly: 'Repeat every year',
    addSpecialDay: 'Add New Special Day',
    searchJournalist: 'Search journalist...',
    namePlaceholder: 'Name',
    designationPlaceholder: 'Designation',
    emailOptional: 'Email (optional)',
    noJournalist: 'No journalists found',
    addJournalistBtn: 'Add New Journalist',
    journalistNameReq: 'Journalist Name *',
    desigExample: 'Designation (e.g. Senior Reporter)',
    subCount: ' sub',
    noSubCat: 'No sub-categories',
    newSubCat: 'New sub-category...',
    newCatName: 'New category name...',
    addCat: 'Add Category',
    typeNational: 'National',
    typeCultural: 'Cultural',
    typeReligious: 'Religious',
    typeInternational: 'International',

    // Dashboard
    totalArticles: 'Total Articles',
    pageViews: 'Page Views',
    activeUsers: 'Active Users',
    pendingReviews: 'Pending Reviews',
    today: 'today',
    thanYesterday: 'than yesterday',
    editorsWriters: 'editors, writers',
    needsApproval: 'needs approval',

    // AssignmentBoard
    assignmentBoard: 'Assignment Board',
    manageWorkflow: 'Manage your news workflow',
    selfAssignment: 'Self Assignment',
    newAssignment: 'New Assignment',
    waitingApproval: ' Self Assignment(s) waiting for approval',
    view: 'View',
    totalCount: 'Total',
    writingTab: 'Writing',
    reviewTab: 'Review',
    approvedTab: 'Approved',
    selfTab: 'Self',
    filterAll: 'All',
    filterNeedsApproval: 'Needs Approval',
    filterWaiting: 'Waiting',
    filterWriting: 'Writing',
    filterSubmitted: 'Submitted',
    filterReview: 'Review',
    filterApproved: 'Approved',
    filterCorrection: 'Correction',
    filterPublished: 'Published',
    allTypes: 'All Types',

    // Settings
    settingsDesc: 'Manage categories, journalists, sources and positions',
    catAndSub: 'Categories & Sub-categories',
    subCatCount: 'sub-categories',
    addCategory: 'Add new category...',
    addBtn: '+ Add',

    // Categories (Dynamic data translations)
    রাজনীতি: 'Politics',
    অর্থনীতি: 'Economy',
    খেলাধুলা: 'Sports',
    বিনোদন: 'Entertainment',
    প্রযুক্তি: 'Technology',
    পরিবেশ: 'Environment',
    মতামত: 'Opinion',
  }
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('cms_lang') || 'bn')

  const toggleLang = () => {
    const next = lang === 'bn' ? 'en' : 'bn'
    setLang(next)
    localStorage.setItem('cms_lang', next)
  }

  const t = translations[lang]

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
